apiVersion: v1
kind: Secret
metadata:
  name: junk-mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: password
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: junk-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: junk-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: junk-mysql
spec:
  selector:
    matchLabels:
      app: junk-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: junk-mysql
    spec:
      containers:
      - image: junk-mysql:latest
        name: junk-mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: junk-mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: junk-mysql
        volumeMounts:
        - name: junk-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: junk-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: junk-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: junk-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: junk-mysql
---
