apiVersion: apps/v1
kind: Deployment
metadata:
  name: junkiapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junkiapp-backend
  template:
    metadata:
      labels:
        app: junkiapp-backend
    spec:
      containers:
      - name: my-http-container
        image: junkiapp-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: junkiapp-backend-svc
spec:
  selector:
    app: junkiapp-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
